// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    // apiKey: 'AIzaSyAVWOQLYGpddjSyVChZ7NnVvmzy-NK_dLg',
    // appId: '1:14678004653:web:c53fb6155960c0f054c724',
    // messagingSenderId: '14678004653',
    // projectId: 'flutter-project-application1',
    // authDomain: 'flutter-project-application1.firebaseapp.com',
    // storageBucket: 'flutter-project-application1.appspot.com',
//  apiKey: "AIzaSyAz9FD7o3HjMyc4-sWVOXQnADm2LoZbFw8",
//   authDomain: "diagnostic-ab05a.firebaseapp.com",
//   projectId: "diagnostic-ab05a",
//   storageBucket: "diagnostic-ab05a.appspot.com",
//   messagingSenderId: "218732047334",
//   appId: "1:218732047334:web:4d3040aeb5632085f90427",
//   measurementId: "G-MJ18RPPDT7"
 apiKey: "AIzaSyAz9FD7o3HjMyc4-sWVOXQnADm2LoZbFw8",
  authDomain: "diagnostic-ab05a.firebaseapp.com",
  databaseURL: "https://diagnostic-ab05a-default-rtdb.firebaseio.com",
  projectId: "diagnostic-ab05a",
  storageBucket: "diagnostic-ab05a.appspot.com",
  messagingSenderId: "218732047334",
  appId: "1:218732047334:web:4d3040aeb5632085f90427",
  measurementId: "G-MJ18RPPDT7"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDogu45DAvRtKhTb3u14t86tT2MUH7lmfc',
    appId: '1:218732047334:android:31296aaf58324229f90427',
    messagingSenderId: '218732047334',
    projectId: 'diagnostic-ab05a',
    storageBucket: 'diagnostic-ab05a.appspot.com',
  databaseURL: "https://diagnostic-ab05a-default-rtdb.firebaseio.com",
  measurementId: "G-MJ18RPPDT7"

  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfqeLMV0HtIM8gP255ZfKiaBKtV49ugNU',
    appId: '1:14678004653:ios:d34c80f0bc9f7f0754c724',
    messagingSenderId: '14678004653',
    projectId: 'flutter-project-application1',
    storageBucket: 'flutter-project-application1.appspot.com',
    iosClientId: '14678004653-gbn1dhm4ianm1q4etcq6lpusp36uo5i5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfqeLMV0HtIM8gP255ZfKiaBKtV49ugNU',
    appId: '1:14678004653:ios:d34c80f0bc9f7f0754c724',
    messagingSenderId: '14678004653',
    projectId: 'flutter-project-application1',
    storageBucket: 'flutter-project-application1.appspot.com',
    iosClientId: '14678004653-gbn1dhm4ianm1q4etcq6lpusp36uo5i5.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );
}
